### PR TITLE
[DG22-1693] Create test deployment for nonprod

### PR DESCRIPTION
**Pull request by kororo**
# [DG22-1693]

## Summary
This pull request addresses the following functionality/fixes:

* Create dummy content changes in BESS1 to test the `nonprod` deployment

## Technical changes
This is a summary of technical changes to the codebase.

* Added `&nbsp;` to the end of the description content

## Links and resources
**Links**
- Jira ticket: https://essnsw.atlassian.net/browse/DG22-1693

**Screenshots**
- Content changes highlighted:
image

## Pre deployment tasks
None

## Post deployment tasks

- [ ] Test UI changes

### CODE REVIEW

**Review by k8mckay — COMMENTED** [review]
@kororo could you please confirm that adding these tests does not break anything in dev? (We typically add a specific comment that all tests are passing on the commit)

**Comment by kororo** [comment]
@k8mckay this should be safe, since it is only copy changes. And this will deploy to dev env.

**Review by k8mckay — APPROVED** [review]
LGTM

**Comment by kororo** [comment]
Changes in: https://safeguardestimator.z8.web.core.windows.net/#/residential-solar-battery-certificates

**Pull request merged**
